In [1]:
import pandas as pd
import spacy
from spacy.lang.en.stop_words import STOP_WORDS

In [2]:
cust_labelled = pd.read_csv('A2_customer_churn_labeled.csv')
cust_labelled.head()

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0

In [3]:
cust_labelled.loc[0, 'customer_profile']

'This customer is a 44-year-old female from Spain with a credit score of 585.0. She has been a member for 4.0 years and currently has 2.0 products with a balance of 0.0. She does not have a credit card but is an active member. Her estimated salary is 101728.4609375.'

In [4]:
# Load spaCy's English tokenizer and tagger
nlp = spacy.load("en_core_web_sm")

# Define a function to perform tokenization, stopwords removal, and lemmatization
def preprocess_text(text):
    doc = nlp(text)
    tokens = [token.lemma_ for token in doc if token.text.lower() not in STOP_WORDS]
    return " ".join(tokens)

preprocess_text(cust_labelled.loc[0, 'customer_profile'])

'customer 44 - year - old female Spain credit score 585.0 . member 4.0 year currently 2.0 product balance 0.0 . credit card active member . estimated salary 101728.4609375 .'

In [5]:
cust_labelled['customer_profile_tokenized'] = cust_labelled['customer_profile'].apply(lambda text: preprocess_text(text))
cust_labelled

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,customer_profile_tokenized
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,customer 44 - year - old female Spain credit s...
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,customer 32 - year - old female Germany credit...
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,customer 41 - year - old female Germany credit...
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,customer 45 - year - old female Germany credit...
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,customer 38 - year - old female France credit ...
...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,customer 35 - year - old female Germany credit...
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,customer 27 - year - old female France credit ...
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,customer 29 - year - old male France credit sc...
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,customer 40 - year - old male France credit sc...
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,customer 67 - year - old female Spain credit s...

In [6]:
cust_labelled.to_csv('A2_customer_churn_labeled_NLP.csv', index=False)