In [1]:
import pandas as pd
import re

In [5]:
df = pd.read_csv("A2_customer_churn_labeled.csv")

In [6]:
df

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0
...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0

In [4]:
df.info

<bound method DataFrame.info of         ID  credit_score  tenure    balance  number_of_products  \
0        0           585       4       0.00                   2
1        1           743       6  140348.56                   2
2        2           527      10  136733.23                   1
3        3           732       6   98792.40                   1
4        4           641       3       0.00                   2
...    ...           ...     ...        ...                 ...
6995  6995           778       1  151958.19                   3
6996  6996           781       5       0.00                   2
6997  6997           738       2       0.00                   2
6998  6998           512       5       0.00                   2
6999  6999           732       1       0.00                   2

      has_credit_card  is_active_member     salary  \
0                   0                 1  101728.46
1                   1                 1  163254.39
2                   1                 1   57589.29
3                   1                 0   81491.70
4                   1                 0  116466.19
...               ...               ...        ...
6995                1                 1  131238.38
6996                0                 0   72969.90
6997                1                 1  170421.12
6998                1                 1  146457.83
6999                1                 1  177783.05

                                       customer_profile  Y
0     This customer is a 44-year-old female from Spa...  0
1     This customer is a 32-year-old female from Ger...  0
2     This customer is a 41-year-old female from Ger...  0
3     This customer is a 45-year-old female from Ger...  1
4     This customer is a 38-year-old female from Fra...  0
...                                                 ... ..
6995  This customer is a 35-year-old female from Ger...  1
6996  This customer is a 27-year-old female from Fra...  0
6997  This customer is a 29-year-old male from Franc...  0
6998  This customer is a 40-year-old male from Franc...  0
6999  This customer is a 67-year-old female from Spa...  0

[7000 rows x 10 columns]>

In [5]:
df.describe

<bound method NDFrame.describe of         ID  credit_score  tenure    balance  number_of_products  \
0        0           585       4       0.00                   2
1        1           743       6  140348.56                   2
2        2           527      10  136733.23                   1
3        3           732       6   98792.40                   1
4        4           641       3       0.00                   2
...    ...           ...     ...        ...                 ...
6995  6995           778       1  151958.19                   3
6996  6996           781       5       0.00                   2
6997  6997           738       2       0.00                   2
6998  6998           512       5       0.00                   2
6999  6999           732       1       0.00                   2

      has_credit_card  is_active_member     salary  \
0                   0                 1  101728.46
1                   1                 1  163254.39
2                   1                 1   57589.29
3                   1                 0   81491.70
4                   1                 0  116466.19
...               ...               ...        ...
6995                1                 1  131238.38
6996                0                 0   72969.90
6997                1                 1  170421.12
6998                1                 1  146457.83
6999                1                 1  177783.05

                                       customer_profile  Y
0     This customer is a 44-year-old female from Spa...  0
1     This customer is a 32-year-old female from Ger...  0
2     This customer is a 41-year-old female from Ger...  0
3     This customer is a 45-year-old female from Ger...  1
4     This customer is a 38-year-old female from Fra...  0
...                                                 ... ..
6995  This customer is a 35-year-old female from Ger...  1
6996  This customer is a 27-year-old female from Fra...  0
6997  This customer is a 29-year-old male from Franc...  0
6998  This customer is a 40-year-old male from Franc...  0
6999  This customer is a 67-year-old female from Spa...  0

[7000 rows x 10 columns]>

In [6]:
df['customer_profile']

0       This customer is a 44-year-old female from Spa...
1       This customer is a 32-year-old female from Ger...
2       This customer is a 41-year-old female from Ger...
3       This customer is a 45-year-old female from Ger...
4       This customer is a 38-year-old female from Fra...
                              ...
6995    This customer is a 35-year-old female from Ger...
6996    This customer is a 27-year-old female from Fra...
6997    This customer is a 29-year-old male from Franc...
6998    This customer is a 40-year-old male from Franc...
6999    This customer is a 67-year-old female from Spa...
Name: customer_profile, Length: 7000, dtype: object

This customer is a 44-year-old female from Spain with a credit score of 585.0. She has been a member for 4.0 years and currently has 2.0 products with a balance of 0.0. She does not have a credit card but is an active member. Her estimated salary is 101728.4609375.

In [7]:
df['age'] = df['customer_profile'].apply(lambda x: int(re.findall('(\d+)-year-old', x)[0]))

In [8]:
df

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,age
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,44
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,32
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,41
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,45
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,38
...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,35
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,27
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,29
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,40
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,67

In [9]:
df['gender'] = df['customer_profile'].apply(lambda x: re.findall('(male|female)', x)[0])

In [10]:
df

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,age,gender
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,44,female
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,32,female
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,41,female
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,45,female
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,38,female
...,...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,35,female
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,27,female
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,29,male
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,40,male
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,67,female

In [11]:
df['country'] = df['customer_profile'].apply(lambda x: re.findall('from (\w+)', x)[0])

In [12]:
df

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,age,gender,country
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,44,female,Spain
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,32,female,Germany
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,41,female,Germany
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,45,female,Germany
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,38,female,France
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,35,female,Germany
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,27,female,France
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,29,male,France
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,40,male,France
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,67,female,Spain

In [13]:
df.to_csv('regex_cols_included.csv', index=False)

In [227]:

df['credit_score_from_text'] = df['customer_profile'].apply(lambda x: float(re.findall('credit score of (\d+.\d)', x)[0]))

In [228]:
null_values = df['credit_score_from_text'].isnull().sum()
print(f'There are {null_values} null/missing values in the credit_score_from_text column.')

There are 0 null/missing values in the credit_score_from_text column.

In [229]:
comparison = df['credit_score_from_text'] == df['credit_score']
print(f'There are {comparison.sum()} rows where credit_score_from_text is equal to credit_score.')

There are 7000 rows where credit_score_from_text is equal to credit_score.

In [230]:
df

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,age,gender,country,credit_score_from_text
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,44,female,Spain,585.0
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,32,female,Germany,743.0
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,41,female,Germany,527.0
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,45,female,Germany,732.0
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,38,female,France,641.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,35,female,Germany,778.0
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,27,female,France,781.0
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,29,male,France,738.0
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,40,male,France,512.0
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,67,female,Spain,732.0

In [231]:
def extract_tenure(x):
    match = re.findall('(member|customer) for (\d+.\d)', x)
    if match:
        return float(match[0][1])
    else:
        match = re.findall('has been a customer for (\w+|\d+.\d)', x)
        if match:
            try:
                return float(match[0])
            except ValueError:
                if match[0] == 'one':
                    return 1.0
        match = re.findall('has only been with the bank for (\w+|\d+.\d) tenure', x)
        if match:
            try:
                return float(match[0])
            except ValueError:
                if match[0] == 'one':
                    return 1.0
        match = re.findall('has been with the bank for only (\w+|\d+.\d)', x)
        if match:
            try:
                return float(match[0])
            except ValueError:
                if match[0] == 'one':
                    return 1.0
        match = re.findall('has been with the bank for (\d+.\d)', x)
        if match:
            return float(match[0])
        match = re.findall('has been with the company for (\w+|\d+.\d)', x)
        if match:
            try:
                return float(match[0])
            except ValueError:
                if match[0] == 'one':
                    return 1.0
        match = re.findall('has only been with the bank for (\w+)', x)
        if match:
            try:
                return float(match[0])
            except ValueError:
                if match[0] == 'one':
                    return 1.0
    return None

In [232]:
df['tenure_from_text'] = df['customer_profile'].apply(extract_tenure)

In [233]:
df

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,age,gender,country,credit_score_from_text,tenure_from_text
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,44,female,Spain,585.0,4.0
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,32,female,Germany,743.0,6.0
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,41,female,Germany,527.0,10.0
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,45,female,Germany,732.0,6.0
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,38,female,France,641.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,35,female,Germany,778.0,1.0
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,27,female,France,781.0,5.0
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,29,male,France,738.0,2.0
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,40,male,France,512.0,5.0
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,67,female,Spain,732.0,1.0

In [234]:
null_values = df['tenure_from_text'].isnull().sum()
print(f'There are {null_values} null/missing values in the tenure_from_text column.')

There are 211 null/missing values in the tenure_from_text column.

In [235]:
# Create a boolean mask for rows where 'tenure_from_text' is not null
mask = df['tenure_from_text'].notnull()

# Compare the columns only for rows where 'tenure_from_text' is not null
comparison = (df['tenure_from_text'][mask] == df['tenure'][mask])

print(f'There are {comparison.sum()} rows where tenure_from_text is equal to tenure.')

There are 6789 rows where tenure_from_text is equal to tenure.

In [236]:
null_rows = df[df['tenure_from_text'].isnull()]
null_rows

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,age,gender,country,credit_score_from_text,tenure_from_text
12,12,778,0,105617.73,2,1,1,133699.81,This customer is a 37-year-old female from Ger...,1,37,female,Germany,778.0,NaN
41,41,726,0,185734.75,1,1,1,102036.82,This customer is a 34-year-old female from Fra...,0,34,female,France,726.0,NaN
55,55,581,0,53291.86,1,0,0,196582.28,This customer is a 30-year-old male from Spain...,0,30,male,Spain,581.0,NaN
75,75,548,0,101084.36,1,1,0,42749.85,This customer is a 33-year-old female from Ger...,0,33,female,Germany,548.0,NaN
87,87,504,0,54980.81,1,1,1,136909.88,This customer is a 34-year-old male from Spain...,0,34,male,Spain,504.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6855,6855,696,0,0.00,2,1,1,9002.80,This customer is a 30-year-old female from Spa...,0,30,female,Spain,696.0,NaN
6880,6880,763,0,152582.20,2,0,0,31892.82,This customer is a 38-year-old female from Fra...,0,38,female,France,763.0,NaN
6892,6892,824,0,133634.02,1,1,1,162053.92,This customer is a 30-year-old male from Franc...,0,30,male,France,824.0,NaN
6982,6982,573,0,90124.64,1,1,0,137476.70,This customer is a 33-year-old female from Fra...,0,33,female,France,573.0,NaN
6989,6989,678,0,107379.68,1,1,1,84460.18,This customer is a 36-year-old male from Franc...,0,36,male,France,678.0,NaN

In [237]:
non_zero_tenure_rows = null_rows[null_rows['tenure'] != 0]
len(non_zero_tenure_rows)

2

In [238]:
zero_tenure_rows = null_rows[null_rows['tenure'] == 0]
len(zero_tenure_rows)

209

In [239]:
for profile in zero_tenure_rows['customer_profile']:
    print(profile)

This customer is a 37-year-old female from Germany with a credit score of 778.0. She has a high estimated salary of 133699.8125 and a substantial balance of 105617.7265625. She has two products with the bank, including a credit card, and is an active member. Despite her tenure being 0.0, her financial stability and creditworthiness make her an ideal customer for the bank.
This customer is a 34-year-old female from France with a credit score of 726.0. She has a balance of 185734.75 and has one product with the bank. She also has a credit card and is an active member. Her estimated salary is 102036.8203125.
This customer is a 30-year-old male from Spain with a credit score of 581.0. He has a balance of 53291.859375 and only one product with the bank. He does not have a credit card and is not an active member. His estimated salary is 196582.28125.
This customer is a 33-year-old female from Germany with a credit score of 548.0. She has a balance of 101084.359375 and only one product with the bank, which is a credit card. She is not an active member and has no tenure with the bank. Her estimated salary is 42749.8515625.
This customer is a 34-year-old male from Spain with a credit score of 504.0. He has a balance of 54980.80859375 and has one product with the bank. He also has a credit card and is an active member. His estimated salary is 136909.875.
This customer is a 32-year-old male from France with a credit score of 694.0. He has a balance of 91956.4921875 and has one product with the bank. He also has a credit card and is an active member. His estimated salary is 59961.80859375.
This customer is a 33-year-old female from France with a credit score of 704.0. She has a balance of 130499.09375 and holds two products with the bank. She has a credit card and is an active member. Her estimated salary is 74804.359375.
This customer is a 45-year-old female from Spain with a credit score of 689.0. She has a balance of 57784.21875 and one product with the bank, which includes a credit card. She is not an active member of the bank and has no tenure with the bank. Her estimated salary is 197804.0.
This customer is a 39-year-old female from France with an excellent credit score of 850.0. She has a high balance of 104386.53125 and holds one product with the bank. She has a credit card and a high estimated salary of 105886.7734375. However, she is not an active member of the bank and has no tenure with the bank.
This customer is a 31-year-old male from Spain with a credit score of 564.0. He has a balance of 125175.578125 and has one product with the bank. He also has a credit card and is an active member. His estimated salary is 72757.328125.
This customer is a 37-year-old male from France with a credit score of 620.0. He has a balance of 107548.9375 and only one product with the bank, which is a credit card. He is not an active member and has no tenure with the bank. His estimated salary is 71175.9375.
This customer is a 40-year-old male from France with a credit score of 717.0. He has a balance of 98241.0390625 and only one product with the bank. He has a credit card and an estimated salary of 110887.140625. However, he is not an active member of the bank and has no tenure with the bank.
This customer is a 33-year-old female from Germany with a credit score of 786.0. She has a balance of 122325.578125 and only one product with the bank. She does not have a credit card and is not an active member. Her estimated salary is 34712.33984375.
This customer is a 32-year-old male from Germany with a credit score of 667. He has a balance of 103846.6484375 and holds one product with the bank. He has a credit card and an estimated salary of 20560.689453125. However, he is not an active member of the bank.
This customer is a 32-year-old female from Germany with an excellent credit score of 850.0. She has a high estimated salary of 175094.625 and a substantial balance of 116968.90625. She currently has one product with the bank and does not have a credit card or active membership.
This customer is a 59-year-old female from Germany with a credit score of 806.0. She has a balance of 135296.328125 and only one product with the bank, which is a credit card. She is not an active member of the bank and has no tenure with the bank. Her estimated salary is 182822.5.
This customer is a 44-year-old female from Spain with a credit score of 637.0. She has a balance of 157622.578125 and has one product with the bank. She has a credit card and is an active member. Her estimated salary is 120454.203125.
This customer is a 45-year-old male from Germany with a credit score of 689.0. He has a balance of 130170.8203125 and holds two products with the bank, including a credit card. He is not an active member of the bank and has no tenure with the institution. His estimated salary is 150856.375.
This customer is a 47-year-old male from Germany with a credit score of 669.0. He has a balance of 63723.78125 and holds two products with the bank, including a credit card. He is an active member and has an estimated salary of 181928.25.
This customer is a 24-year-old female from France with a credit score of 736.0. She currently has two products with the bank, including a credit card. Although she is a new customer with a tenure of 0.0, her estimated salary is high at 109355.7265625. However, she is not an active member and has a balance of 0.0.
This customer is a 28-year-old female from France with a credit score of 597.0. She has a high balance of 142705.953125 and holds one product with the bank. She has a credit card and a high estimated salary of 127233.390625. However, she is not an active member of the bank and has no tenure with the bank.
This customer is a 55-year-old male from Germany with a credit score of 850.0. He has a balance of 98710.890625 and holds one product with the bank. He has a credit card and is an active member. His estimated salary is 83617.171875.
This customer is a 36-year-old female from Spain with a credit score of 624.0. She currently has two products with the bank, including a credit card. Although she is a new customer with a tenure of 0.0 and a balance of 0.0, her estimated salary is relatively high at 111605.8984375. However, she is not an active member of the bank.
This customer is a 40-year-old female from Spain with a credit score of 698.0. She has a balance of 92053.4375 and one product with the bank, which includes a credit card. She is an active member and has an estimated salary of 143681.828125.
This customer is a 36-year-old male from Spain with an excellent credit score of 850.0. He currently has two products with the bank, including a credit card. Although he is a new customer with a tenure of 0.0, his estimated salary is high at 141242.5625. However, he is not an active member and has a balance of 0.0.
This customer is a 40-year-old male from France with a credit score of 748.0. He has no tenure with the bank and currently has a balance of 0.0. He has one product with the bank but does not have a credit card and is not an active member. His estimated salary is 60416.76171875.
This customer is a 54-year-old female from Spain with a credit score of 682.0. She has a balance of 83102.71875 and holds two products with the bank, including a credit card. She is an active member and has an estimated salary of 54132.9296875.
This customer is a 50-year-old male from Spain with a credit score of 573.0. He has no tenure with the bank and currently holds one product. He does not have a credit card but is an active member. His estimated salary is 155,915.23 and he has a balance of 159,304.06.
This customer is a 35-year-old male from France with a credit score of 651.0. He has a balance of 181821.953125 and holds two products with the bank. He does not have a credit card but is an active member. His estimated salary is 36923.671875.
This customer is a 40-year-old female from Germany with a credit score of 618.0. She has a balance of 140306.375 and only one product with the bank, which is a credit card. She is not an active member and has no tenure with the bank. Her estimated salary is 160618.609375.
This customer is a 24-year-old female from France with a credit score of 764.0. She currently has two products with the bank, including a credit card. Although she is a new customer with a tenure of 0.0, her estimated salary is high at 88724.4921875. However, she is not an active member and has a balance of 0.0.
This customer is a 68-year-old male from Germany with a credit score of 672.0. He has a balance of 126061.5078125 and holds two products with the bank, including a credit card. He is an active member and has an estimated salary of 184936.765625.
This customer is a 33-year-old female from France with a credit score of 593.0. She has a balance of 95927.0390625 and only one product with the bank, which is a credit card. She is not an active member of the bank and has no tenure with the bank. Her estimated salary is 199478.046875.
This customer is a 20-year-old male from France with a credit score of 781.0. He has a high estimated salary of 108301.453125 and a substantial balance of 125023.1015625. He has two products with the bank, including a credit card, and is an active member. Despite being a new customer with a tenure of 0.0, his financial profile suggests he is a responsible and valuable customer.
This customer is a 30-year-old female from France with a credit score of 560.0. She has a balance of 108883.2890625 and only one product with the bank, which is a credit card. She is not an active member and has no tenure with the bank. Her estimated salary is 27914.94921875.
This customer is a 34-year-old female from France with a credit score of 661.0. She currently has two products with the bank, including a credit card. Although she is a new customer with a tenure of 0.0, her estimated salary is 185555.625. However, she is not an active member and has a balance of 0.0.
This customer is a 30-year-old female from Germany with a credit score of 525.0. She has a high balance of 157989.203125 and holds two products with the bank, including a credit card. Despite her low credit score, she is an active member of the bank and has an estimated salary of 100687.671875.
This customer is a 46-year-old female from France with a credit score of 698.0. She has two products with the bank, including a credit card, and is an active member. Her estimated salary is 125962.0234375, and she currently has a balance of 0.0.
This customer is a 35-year-old female from Spain with a credit score of 677.0. She currently has 2 products with the bank but no credit card and is not an active member. Her estimated salary is 76637.3828125 and she has no balance or tenure with the bank.
This customer is a 42-year-old female from Germany with a credit score of 530.0. She has a tenure of 0.0 and a balance of 99948.453125. She has one product with the bank and does not have a credit card. However, she is an active member and has an estimated salary of 97338.6171875.
This customer is a 47-year-old male from Spain with a credit score of 792.0. He has a tenure of 0.0 and a balance of 0.0, but has one product with the bank and a credit card. He is an active member and has an estimated salary of 5557.8798828125.
This customer is a 29-year-old male from France with a credit score of 411.0. He has a balance of 59697.171875 and holds two products with the bank. He has a credit card and is an active member. His estimated salary is 53483.2109375.
This customer is a 37-year-old female from Spain with a credit score of 734.0. She has a balance of 152760.234375 and has one product with the bank, which is a credit card. She is an active member and has an estimated salary of 48990.5.
This customer is a 31-year-old male from Spain with a credit score of 794.0. He has a high estimated salary of 175643.4375 and a substantial balance of 144880.34375. He currently has two products with the bank and is an active member, but does not have a credit card.
This customer is a 47-year-old female from Germany with a credit score of 661.0. She has a balance of 109493.6171875 and only one product with the bank. She does not have a credit card and is not an active member. Her estimated salary is 188324.015625.
This customer is a 42-year-old male from France with a credit score of 682.0. He has a tenure of 0.0 and a balance of 0.0, but has one product with the bank and holds a credit card. He is an active member and has an estimated salary of 160828.984375.
This customer is a 32-year-old female from Spain with a credit score of 673.0. She has a tenure of 0.0 and a balance of 0.0, but holds one product with the bank and has a credit card. She is an active member and has an estimated salary of 72873.328125.
This customer is a 30-year-old male from Spain with a credit score of 678.0. He has a tenure of 0.0 and a balance of 0.0, but has one product with the bank and a credit card. He is not an active member but has an estimated salary of 35113.078125.
This customer is a 40-year-old female from France with a credit score of 350.0. She has a balance of 111098.8515625 and has one product with the bank. She has a credit card and is an active member. Her estimated salary is 172321.203125.
This customer is a 30-year-old male from France with a credit score of 539.0. He currently has two products with the bank, including a credit card. He is not an active member and has no tenure or balance with the bank. However, his estimated salary is high at 160979.65625.
This customer is a 22-year-old male from France with a credit score of 620.0. He has a tenure of 0.0 and a balance of 0.0, but holds one product and has a credit card. He is not an active member and has an estimated salary of 32589.44921875.
This customer is a 60-year-old female from France with a credit score of 597.0. She has a balance of 131778.078125 and only one product with the bank. She does not have a credit card and is not an active member. Her estimated salary is 10703.5302734375.
This customer is a 21-year-old female from France with a credit score of 711.0. She has a balance of 82844.328125 and holds two products with the bank. She does not have a credit card but is an active member. Her estimated salary is 1408.6800537109375.
This customer is a 45-year-old male from France with a credit score of 702.0. He has a balance of 80793.578125 and holds one product with the bank. He has a credit card and is an active member. His estimated salary is 27474.810546875.
This customer is a 41-year-old female from Germany with a credit score of 490.0. She has a high estimated salary of 176254.125 and a large balance of 139659.046875. She has one product with the bank and has a credit card. She is also an active member of the bank.
This customer is a 31-year-old male from France with a credit score of 628.0. He has a balance of 88421.8125 and only one product with the bank. He does not have a credit card and is not an active member. His estimated salary is 72350.46875.
This customer is a 36-year-old male from France with a credit score of 643.0. He has a balance of 148159.703125 and only one product with the bank. He does not have a credit card and is not an active member. His estimated salary is 55835.66015625.
This customer is a 34-year-old male from Spain with a credit score of 559.0. He has no tenure with the bank and currently has a balance of 0.0. He has one product with the bank, a credit card, but is not an active member. His estimated salary is 182988.9375.
This customer is a 35-year-old male from Spain with a credit score of 676.0. He currently has 2 products with the bank but no credit card and is not an active member. He has a tenure of 0.0 and a balance of 0.0. His estimated salary is 139911.578125.
This customer is a 71-year-old female from France with a credit score of 757.0. She has a balance of 88084.1328125 and holds two products with the bank. She has a credit card and is an active member. Her estimated salary is 154337.46875.
This customer is a 31-year-old female from Spain with a credit score of 727.0. She currently has one product with the bank, which is a credit card. Although she is not an active member, her estimated salary is high at 121,751.04. Her tenure with the bank is 0.0 and her balance is currently at 0.0.
This customer is a 52-year-old female from France with a credit score of 626.0. She currently has two products with the bank, including a credit card. Although she is not an active member, her estimated salary is 32159.4609375. She has no balance and no tenure with the bank.
This customer is a 31-year-old male from Germany with a credit score of 573.0. He has a balance of 134644.1875 and has one product with the bank, which is a credit card. He is an active member and has an estimated salary of 70381.4921875.
This customer is a 36-year-old female from France with a credit score of 488.0. She currently has two products with the bank, including a credit card. Although she is not an active member, her estimated salary is relatively high at 136675.21875. She has no balance and no tenure with the bank.
This customer is a 62-year-old female from Spain with a credit score of 612.0. She has a balance of 167026.609375 and holds two products with the bank, including a credit card. She is an active member and has an estimated salary of 192892.046875.
This customer is a 39-year-old female from Germany with a credit score of 638.0. She has a balance of 122501.28125 and holds two products with the bank, including a credit card. She is an active member and has an estimated salary of 95007.796875.
This customer is a 55-year-old female from France with a credit score of 619.0. She currently has three products with the bank but has a balance and tenure of 0.0. She does not have a credit card and is not an active member. Her estimated salary is 60810.640625.
This customer is a 36-year-old male from France with a credit score of 709.0. He currently has two products with the bank, including a credit card. Although he is a new customer with a tenure of 0.0, he has a good credit score and an estimated salary of 46811.76953125. However, he is not an active member and has a balance of 0.0.
This customer is a 64-year-old male from France with a credit score of 615.0. He has a balance of 81564.1015625 and holds two products with the bank. He does not have a credit card but is an active member. His estimated salary is 35896.08984375.
This customer is a 20-year-old male from France with a credit score of 539.0. He has a balance of 83459.859375 and has one product with the bank. He has a credit card and is an active member. His estimated salary is 146752.671875.
This customer is a 37-year-old female from Germany with a credit score of 722.0. She has a high estimated salary of 160162.421875 and a large balance of 125977.8125. She currently has one product with the bank and does not have a credit card or active membership.
This customer is a 38-year-old female from France with a credit score of 535.0. She has a balance of 135919.328125 and only one product with the bank, which is a credit card. She is not an active member and has no tenure with the bank. Her estimated salary is 80425.6484375.
This customer is a 46-year-old female from Germany with a credit score of 777.0. She has a balance of 107362.796875 and only one product with the bank, which is a credit card. She is not an active member and has no tenure with the bank. Her estimated salary is 487.29998779296875.
This customer is a 31-year-old male from Germany with a credit score of 611.0. He has a high estimated salary of 183487.984375 and a significant balance of 107884.8125. He has two products with the bank, including a credit card, and is an active member. However, he has no tenure with the bank yet.

In [240]:
non_zero_tenure_rows['tenure']

587     5
6585    1
Name: tenure, dtype: int64

In [276]:
def extract_products(x):
    match = re.findall('(has|holds|has only|only) (\d+\.?\d*|[a-z]+) product[s]?', x)
    if match:
        # If the match is a digit or a decimal number, return it as an integer
        if match[0][1].replace('.', '').isdigit():
            return int(float(match[0][1]))
        # If the match is 'one', return it as an integer
        elif match[0][1] == 'one':
            return 1
    return None

In [277]:
df['number_of_products_from_text'] = df['customer_profile'].apply(extract_products)

In [278]:
different_rows = df[df['number_of_products_from_text'] != df['number_of_products']]

# Print these rows
len(different_rows)

145

In [275]:
for profile in different_rows['customer_profile']:
    print(profile)

This customer is a 37-year-old female from Germany with a credit score of 778.0. She has a high estimated salary of 133699.8125 and a substantial balance of 105617.7265625. She has two products with the bank, including a credit card, and is an active member. Despite her tenure being 0.0, her financial stability and creditworthiness make her an ideal customer for the bank.
This customer is a 32-year-old female from Germany with a credit score of 655.0. She has a balance of 130935.5625 and only one product with the bank, which is a credit card. She has been a customer for 6.0 years but is not an active member. Her estimated salary is 9241.830078125.
This customer is a 30-year-old male from Spain with a credit score of 581.0. He has a balance of 53291.859375 and only one product with the bank. He does not have a credit card and is not an active member. His estimated salary is 196582.28125.
This customer is a 33-year-old female from Germany with a credit score of 548.0. She has a balance of 101084.359375 and only one product with the bank, which is a credit card. She is not an active member and has no tenure with the bank. Her estimated salary is 42749.8515625.
This customer is a 30-year-old male from Germany with a credit score of 637.0. He has a balance of 122185.53125 and only one product with the bank, which is a credit card. He has been a customer for 1.0 year but is not an active member. His estimated salary is 102566.4609375.
This customer is a 33-year-old female from France with a credit score of 704.0. She has a balance of 130499.09375 and holds two products with the bank. She has a credit card and is an active member. Her estimated salary is 74804.359375.
This customer is a 45-year-old female from Spain with a credit score of 689.0. She has a balance of 57784.21875 and one product with the bank, which includes a credit card. She is not an active member of the bank and has no tenure with the bank. Her estimated salary is 197804.0.
This customer is a 28-year-old female from Spain with a credit score of 689.0. She has a balance of 95328.6015625 and only one product with the bank, which is a credit card. She has been a customer for 5.0 years but is not an active member. Her estimated salary is 6129.60986328125.
This customer is a 31-year-old male from Spain with a credit score of 744.0. He has a balance of 117551.2265625 and only one product with the bank, which is a credit card. He is not an active member of the bank and has been with the bank for 0.0 tenure. His estimated salary is 158958.90625.
This customer is a 35-year-old female from Spain with a credit score of 661.0. She has a balance of 128415.453125 and only one product with the bank, which is a credit card. She has been a customer for 5.0 years but is not an active member. Her estimated salary is 142626.484375.
This customer is a 40-year-old male from Germany with an excellent credit score of 850.0. He has been a customer for 4.0 years and currently has a balance of 166082.15625. He has two products with the bank and is an active member. Although he does not have a credit card with the bank, his estimated salary is 44406.171875.
This customer is a 60-year-old female from Germany with a credit score of 756.0. She has a balance of 115924.890625 and only one product with the bank, which is a credit card. She has been a customer for 3.0 years and is not an active member. Her estimated salary is 93524.1875.
This customer is a 52-year-old female from Germany with a credit score of 698.0. She has a balance of 107906.75 and only one product with the bank, which is a credit card. She has been a customer for one year but is not an active member. Her estimated salary is 168886.390625.
This customer is a 46-year-old male from France with a credit score of 684.0. He has been a member for 0.0 years and currently has a balance of 0.0. He has two products with the company and has a credit card. He is an active member and has an estimated salary of 36376.96875.
This customer is an 18-year-old male from Spain with a credit score of 677.0. He has been a member for 8.0 years and has a balance of 134796.875. He has two products with the company and has a credit card. He is an active member and has an estimated salary of 114858.8984375.
This customer is a 37-year-old male from France with a credit score of 620.0. He has a balance of 107548.9375 and only one product with the bank, which is a credit card. He is not an active member and has no tenure with the bank. His estimated salary is 71175.9375.
This customer is a 40-year-old male from France with a credit score of 717.0. He has a balance of 98241.0390625 and only one product with the bank. He has a credit card and an estimated salary of 110887.140625. However, he is not an active member of the bank and has no tenure with the bank.
This customer is a 27-year-old female from Spain with a credit score of 559.0. She has been a member for 1.0 year and has an estimated salary of 1050.3299560546875. She currently has a balance of 0.0 and only one product with the company. She does not have a credit card but is an active member.
This customer is a 33-year-old female from Germany with a credit score of 786.0. She has a balance of 122325.578125 and only one product with the bank. She does not have a credit card and is not an active member. Her estimated salary is 34712.33984375.
This customer is a 44-year-old male from Germany with an excellent credit score of 850.0. He has been a customer for 2.0 years and currently has a balance of 112755.34375. He has two products with the bank but does not have a credit card and is not an active member. His estimated salary is 158171.359375.
This customer is a 30-year-old female from Germany with a credit score of 551.0. She has a balance of 143340.4375 and only one product with the bank, which is a credit card. She has been a customer for 2.0 years but is not an active member. Her estimated salary is 145796.484375.
This customer is a 59-year-old female from Germany with a credit score of 806.0. She has a balance of 135296.328125 and only one product with the bank, which is a credit card. She is not an active member of the bank and has no tenure with the bank. Her estimated salary is 182822.5.
This customer is a 39-year-old male from France with an excellent credit score of 850.0. He has been a customer for 4.0 years and currently has a balance of 127771.3515625. He has two products with the bank and is an active member, but does not have a credit card. His estimated salary is 151738.546875.
This customer is a 55-year-old female from Germany with a credit score of 689.0. She has a balance of 76296.8125 and only one product with the bank, which is a credit card. She has been a customer for one year but is not an active member. Her estimated salary is 42364.75.
This customer is a 45-year-old male from Germany with a credit score of 689.0. He has a balance of 130170.8203125 and holds two products with the bank, including a credit card. He is not an active member of the bank and has no tenure with the institution. His estimated salary is 150856.375.
This customer is a 47-year-old male from Germany with a credit score of 669.0. He has a balance of 63723.78125 and holds two products with the bank, including a credit card. He is an active member and has an estimated salary of 181928.25.
This customer is a 24-year-old female from France with a credit score of 736.0. She currently has two products with the bank, including a credit card. Although she is a new customer with a tenure of 0.0, her estimated salary is high at 109355.7265625. However, she is not an active member and has a balance of 0.0.
This customer is a 25-year-old female from France with a credit score of 602.0. She has two products with the bank, including a credit card, and is an active member. Her estimated salary is 101274.171875, but she currently has a balance of 0.0 and has been with the bank for 0.0 years.
This customer is a 36-year-old female from Spain with a credit score of 624.0. She currently has two products with the bank, including a credit card. Although she is a new customer with a tenure of 0.0 and a balance of 0.0, her estimated salary is relatively high at 111605.8984375. However, she is not an active member of the bank.
This customer is a 40-year-old female from Spain with a credit score of 698.0. She has a balance of 92053.4375 and one product with the bank, which includes a credit card. She is an active member and has an estimated salary of 143681.828125.
This customer is a 43-year-old female from Germany with a credit score of 737.0. She has a balance of 125537.3828125 and only one product with the bank, which is a credit card. She has been a customer for 1.0 year but is not an active member. Her estimated salary is 138510.015625.
This customer is a 35-year-old female from Germany with a credit score of 717.0. She has a balance of 103214.7109375 and only one product with the bank, which is a credit card. She has been a customer for 5.0 years but is not an active member. Her estimated salary is 172172.703125.
This customer is a 36-year-old male from Spain with an excellent credit score of 850.0. He currently has two products with the bank, including a credit card. Although he is a new customer with a tenure of 0.0, his estimated salary is high at 141242.5625. However, he is not an active member and has a balance of 0.0.
This customer is a 54-year-old female from Spain with a credit score of 682.0. She has a balance of 83102.71875 and holds two products with the bank, including a credit card. She is an active member and has an estimated salary of 54132.9296875.
This customer is a 47-year-old male from France with a credit score of 590.0. He has a balance of 117879.3203125 and has been a customer for 0.0 years with one product. He has a credit card and is an active member. His estimated salary is 8214.4599609375.
This customer is a 35-year-old male from France with a credit score of 651.0. He has a balance of 181821.953125 and holds two products with the bank. He does not have a credit card but is an active member. His estimated salary is 36923.671875.
This customer is a 40-year-old female from Germany with a credit score of 618.0. She has a balance of 140306.375 and only one product with the bank, which is a credit card. She is not an active member and has no tenure with the bank. Her estimated salary is 160618.609375.
This customer is a 24-year-old female from France with a credit score of 764.0. She currently has two products with the bank, including a credit card. Although she is a new customer with a tenure of 0.0, her estimated salary is high at 88724.4921875. However, she is not an active member and has a balance of 0.0.
This customer is a 68-year-old male from Germany with a credit score of 672.0. He has a balance of 126061.5078125 and holds two products with the bank, including a credit card. He is an active member and has an estimated salary of 184936.765625.
This customer is a 33-year-old female from France with a credit score of 593.0. She has a balance of 95927.0390625 and only one product with the bank, which is a credit card. She is not an active member of the bank and has no tenure with the bank. Her estimated salary is 199478.046875.
This customer is a 34-year-old female from Germany with a credit score of 760.0. She has a balance of 58003.41015625 and one product with the bank, which includes a credit card. She has been a customer for 6.0 years but is not an active member. Her estimated salary is 90346.1015625.
This customer is a 20-year-old male from France with a credit score of 781.0. He has a high estimated salary of 108301.453125 and a substantial balance of 125023.1015625. He has two products with the bank, including a credit card, and is an active member. Despite being a new customer with a tenure of 0.0, his financial profile suggests he is a responsible and valuable customer.
This customer is a 30-year-old female from France with a credit score of 560.0. She has a balance of 108883.2890625 and only one product with the bank, which is a credit card. She is not an active member and has no tenure with the bank. Her estimated salary is 27914.94921875.
This customer is a 34-year-old female from France with a credit score of 661.0. She currently has two products with the bank, including a credit card. Although she is a new customer with a tenure of 0.0, her estimated salary is 185555.625. However, she is not an active member and has a balance of 0.0.
This customer is a 31-year-old female from France with a credit score of 594.0. She has a balance of 79340.953125 and only one product with the bank, which is a credit card. She is not an active member and has been with the bank for 0.0 tenure. Her estimated salary is 78255.859375.
This customer is a 42-year-old female from Germany with a credit score of 651.0. She has a balance of 116646.7578125 and only one product with the bank, which is a credit card. She has been a customer for 1.0 year but is not an active member. Her estimated salary is 44731.80078125.
This customer is a 38-year-old female from France with a credit score of 715.0. She has been a member for 0.0 years and currently has a balance of 0.0. She has two products with the bank, including a credit card, and is an active member. Her estimated salary is 332.80999755859375.
This customer is a 39-year-old male from France with a credit score of 679.0. He has a balance of 86843.609375 and has been a customer for 0.0 years with only one product. He does not have a credit card but is an active member. His estimated salary is 159830.578125.
This customer is a 30-year-old female from Germany with a credit score of 525.0. She has a high balance of 157989.203125 and holds two products with the bank, including a credit card. Despite her low credit score, she is an active member of the bank and has an estimated salary of 100687.671875.
This customer is a 36-year-old female from France with a credit score of 634.0. She has a balance of 69518.953125 and only one product with the bank, which is a credit card. She has been a customer for 1.0 year but is not an active member. Her estimated salary is 116238.390625.
This customer is a 39-year-old female from France with a credit score of 446.0. She has a balance of 90217.0703125 and only one product with the bank, which is a credit card. She is not an active member of the bank and has been with the bank for only 1.0 year. Her estimated salary is 191350.484375.
This customer is a 48-year-old female from Spain with a credit score of 764.0. She has a balance of 75990.96875 and only one product with the bank, which is a credit card. She has been a customer for 1.0 year but is not an active member. Her estimated salary is 158323.8125.
This customer is a 46-year-old female from France with a credit score of 698.0. She has two products with the bank, including a credit card, and is an active member. Her estimated salary is 125962.0234375, and she currently has a balance of 0.0.
This customer is a 33-year-old female from France with a credit score of 596.0. She has a balance of 138162.8125 and only one product with the bank, which is a credit card. She has been a customer for 1.0 year but is not an active member. Her estimated salary is 85412.5390625.
This customer is a 29-year-old male from France with a credit score of 411.0. He has a balance of 59697.171875 and holds two products with the bank. He has a credit card and is an active member. His estimated salary is 53483.2109375.
This customer is a 66-year-old male from France with an excellent credit score of 850.0. He has been a customer for 4.0 years and currently has a balance of 0.0. He has two products with the bank but does not have a credit card. He is an active member and has an estimated salary of 64350.80078125.
This customer is a 31-year-old male from Spain with a credit score of 794.0. He has a high estimated salary of 175643.4375 and a substantial balance of 144880.34375. He currently has two products with the bank and is an active member, but does not have a credit card.
This customer is a 47-year-old female from Germany with a credit score of 661.0. She has a balance of 109493.6171875 and only one product with the bank. She does not have a credit card and is not an active member. Her estimated salary is 188324.015625.
This customer is a 50-year-old female from Spain with a credit score of 584.0. She has been a member for 1.0 year and has an estimated salary of 152567.75. She currently has 0.0 balance and only 1.0 product with no credit card. However, she is an active member.
This customer is a 53-year-old male from Germany with an excellent credit score of 850.0. He has been a customer for 2.0 years and currently has a balance of 94078.96875. He has two products with the bank and holds a credit card. However, he is not an active member. His estimated salary is 36980.5390625.
This customer is a 30-year-old male from France with a credit score of 539.0. He currently has two products with the bank, including a credit card. He is not an active member and has no tenure or balance with the bank. However, his estimated salary is high at 160979.65625.
This customer is a 45-year-old female from Germany with a credit score of 778.0. She has a high estimated salary of 174531.265625 and a substantial balance of 162150.421875. She has two products with the bank, including a credit card. However, she is not an active member and has only been with the bank for one year.
This customer is a 60-year-old female from France with a credit score of 597.0. She has a balance of 131778.078125 and only one product with the bank. She does not have a credit card and is not an active member. Her estimated salary is 10703.5302734375.
This customer is a 21-year-old female from Germany with a credit score of 672.0. She has a balance of 35741.69140625 and only one product with the bank, which is a credit card. She has been a customer for 1.0 year but is not an active member. Her estimated salary is 28789.939453125.
This customer is a 21-year-old female from France with a credit score of 711.0. She has a balance of 82844.328125 and holds two products with the bank. She does not have a credit card but is an active member. Her estimated salary is 1408.6800537109375.
This customer is a 40-year-old female from Spain with a credit score of 705.0. She has a balance of 203715.15625 and one product with the bank, which includes a credit card. She has been a customer for 5.0 years but is not an active member. Her estimated salary is 179978.6875.
This customer is a 46-year-old female from France with a credit score of 586.0. She has been a member for 0.0 years and currently has a balance of 0.0. She has three products with the company and is an active member, but does not have a credit card. Her estimated salary is 131553.8125.
This customer is a 31-year-old male from Spain with an excellent credit score of 850.0. He has been a customer for 6.0 years and currently has a balance of 82613.5625. He has two products with the bank, including a credit card. However, he is not an active member. His estimated salary is 149170.921875.
This customer is a 35-year-old female from Spain with a credit score of 722.0. She has a balance of 120171.578125 and one product with the bank, which includes a credit card. She has been a customer for one year but is not an active member. Her estimated salary is 125240.796875.
This customer is a 36-year-old male from France with a credit score of 512.0. He has a balance of 129804.171875 and only one product with the bank, which is a credit card. He is not an active member and has been with the bank for 0.0 tenure. His estimated salary is 53020.8984375.
This customer is a 31-year-old male from France with a credit score of 628.0. He has a balance of 88421.8125 and only one product with the bank. He does not have a credit card and is not an active member. His estimated salary is 72350.46875.

In [205]:
def extract_balance(x):
    match = re.findall('balance of ([\d,]+.\d+)', x)
    if match:
        # Remove the comma and convert to float
        return float(match[0].replace(',', ''))
    else:
        return None

In [206]:

df['balance_from_text'] = df['customer_profile'].apply(extract_balance)

In [207]:
df

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,age,gender,country,credit_score_from_text,tenure_from_text,number_of_products_from_text,balance_from_text
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,44,female,Spain,585.0,4.0,2.0,0.000000
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,32,female,Germany,743.0,6.0,2.0,140348.562500
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,41,female,Germany,527.0,10.0,1.0,136733.234375
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,45,female,Germany,732.0,6.0,1.0,98792.398438
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,38,female,France,641.0,3.0,2.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,35,female,Germany,778.0,1.0,3.0,151958.187500
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,27,female,France,781.0,5.0,2.0,0.000000
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,29,male,France,738.0,2.0,2.0,NaN
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,40,male,France,512.0,5.0,2.0,0.000000
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,67,female,Spain,732.0,1.0,2.0,NaN

In [208]:
df['has_credit_card_from_text'] = df['customer_profile'].apply(lambda x: 1 if 'has a credit card' in x else (0 if 'product' in x else None))

In [209]:
df

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,age,gender,country,credit_score_from_text,tenure_from_text,number_of_products_from_text,balance_from_text,has_credit_card_from_text
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,44,female,Spain,585.0,4.0,2.0,0.000000,0
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,32,female,Germany,743.0,6.0,2.0,140348.562500,0
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,41,female,Germany,527.0,10.0,1.0,136733.234375,1
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,45,female,Germany,732.0,6.0,1.0,98792.398438,1
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,38,female,France,641.0,3.0,2.0,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,35,female,Germany,778.0,1.0,3.0,151958.187500,0
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,27,female,France,781.0,5.0,2.0,0.000000,0
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,29,male,France,738.0,2.0,2.0,NaN,0
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,40,male,France,512.0,5.0,2.0,0.000000,0
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,67,female,Spain,732.0,1.0,2.0,NaN,0

In [210]:
df['is_active_member_from_text'] = df['customer_profile'].apply(lambda x: 1 if 'is an active member' in x else 0)

In [211]:
df

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,age,gender,country,credit_score_from_text,tenure_from_text,number_of_products_from_text,balance_from_text,has_credit_card_from_text,is_active_member_from_text
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,44,female,Spain,585.0,4.0,2.0,0.000000,0,1
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,32,female,Germany,743.0,6.0,2.0,140348.562500,0,1
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,41,female,Germany,527.0,10.0,1.0,136733.234375,1,1
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,45,female,Germany,732.0,6.0,1.0,98792.398438,1,0
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,38,female,France,641.0,3.0,2.0,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,35,female,Germany,778.0,1.0,3.0,151958.187500,0,1
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,27,female,France,781.0,5.0,2.0,0.000000,0,0
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,29,male,France,738.0,2.0,2.0,NaN,0,1
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,40,male,France,512.0,5.0,2.0,0.000000,0,1
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,67,female,Spain,732.0,1.0,2.0,NaN,0,1

In [212]:
def extract_salary(x):
    match = re.findall('estimated salary is ([\d,]+.\d+)', x)
    if match:
        # Remove the comma and convert to float
        return float(match[0].replace(',', ''))
    else:
        return None

In [213]:
df['salary_from_text'] = df['customer_profile'].apply(extract_salary)

In [214]:
df

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,age,gender,country,credit_score_from_text,tenure_from_text,number_of_products_from_text,balance_from_text,has_credit_card_from_text,is_active_member_from_text,salary_from_text
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,44,female,Spain,585.0,4.0,2.0,0.000000,0,1,101728.460938
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,32,female,Germany,743.0,6.0,2.0,140348.562500,0,1,163254.390625
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,41,female,Germany,527.0,10.0,1.0,136733.234375,1,1,57589.289062
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,45,female,Germany,732.0,6.0,1.0,98792.398438,1,0,81491.703125
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,38,female,France,641.0,3.0,2.0,0.000000,0,0,116466.187500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,35,female,Germany,778.0,1.0,3.0,151958.187500,0,1,131238.375000
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,27,female,France,781.0,5.0,2.0,0.000000,0,0,72969.898438
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,29,male,France,738.0,2.0,2.0,NaN,0,1,NaN
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,40,male,France,512.0,5.0,2.0,0.000000,0,1,146457.828125
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,67,female,Spain,732.0,1.0,2.0,NaN,0,1,NaN