In [1]:
import pandas as pd

In [2]:
cust_labelled = pd.read_csv('A2_customer_churn_labeled.csv')
cust_labelled.head()

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0

In [3]:
cust_labelled.loc[0, 'customer_profile']

'This customer is a 44-year-old female from Spain with a credit score of 585.0. She has been a member for 4.0 years and currently has 2.0 products with a balance of 0.0. She does not have a credit card but is an active member. Her estimated salary is 101728.4609375.'

In [4]:
cust_labelled.loc[0, 'customer_profile'].split('.')

['This customer is a 44-year-old female from Spain with a credit score of 585',
 '0',
 ' She has been a member for 4',
 '0 years and currently has 2',
 '0 products with a balance of 0',
 '0',
 ' She does not have a credit card but is an active member',
 ' Her estimated salary is 101728',
 '4609375',
 '']

In [5]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\UFC\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [6]:
def get_last_two_sentences(text):
    sentences = sent_tokenize(text)

    # Get the last 2 sentences
    last_two_sentences = sentences[-2:]

    return ' '.join(last_two_sentences)

In [7]:
get_last_two_sentences(cust_labelled.loc[0, 'customer_profile'])

'She does not have a credit card but is an active member. Her estimated salary is 101728.4609375.'

In [8]:
cust_labelled['last_lines'] = cust_labelled['customer_profile'].apply(lambda text: get_last_two_sentences(text))
cust_labelled

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,last_lines
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,She does not have a credit card but is an acti...
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,"She has 2.0 products with the bank, including ..."
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,She has one product with the bank and has a cr...
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,"However, she is not an active member. Her esti..."
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,"However, she is not an active member. Her esti..."
...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,"She has 3.0 products with the bank, including ..."
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,She has 2.0 products with the bank but does no...
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,He is an active member and has an estimated sa...
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,"He has 2.0 products with the bank, including a..."
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,She is an active member and has an estimated s...

In [9]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Create an object instance sih of SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

# Function that returns compound polarity score of the text
def get_polarity(text):
    # Get the polarity scores of the passed text
    return sia.polarity_scores(text)['compound']

In [10]:
cust_labelled['customer_profile_polarity'] = cust_labelled['customer_profile'].apply(lambda text: get_polarity(text))
cust_labelled['last_lines_polarity'] = cust_labelled['last_lines'].apply(lambda text: get_polarity(text))
cust_labelled

,ID,credit_score,tenure,balance,number_of_products,has_credit_card,is_active_member,salary,customer_profile,Y,last_lines,customer_profile_polarity,last_lines_polarity
0,0,585,4,0.00,2,0,1,101728.46,This customer is a 44-year-old female from Spa...,0,She does not have a credit card but is an acti...,0.7311,0.4512
1,1,743,6,140348.56,2,1,1,163254.39,This customer is a 32-year-old female from Ger...,0,"She has 2.0 products with the bank, including ...",0.7845,0.6486
2,2,527,10,136733.23,1,1,1,57589.29,This customer is a 41-year-old female from Ger...,0,She has one product with the bank and has a cr...,0.7845,0.6486
3,3,732,6,98792.40,1,1,0,81491.70,This customer is a 45-year-old female from Ger...,1,"However, she is not an active member. Her esti...",0.4482,-0.3089
4,4,641,3,0.00,2,1,0,116466.19,This customer is a 38-year-old female from Fra...,0,"However, she is not an active member. Her esti...",0.4482,-0.3089
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,778,1,151958.19,3,1,1,131238.38,This customer is a 35-year-old female from Ger...,1,"She has 3.0 products with the bank, including ...",0.7845,0.6486
6996,6996,781,5,0.00,2,0,0,72969.90,This customer is a 27-year-old female from Fra...,0,She has 2.0 products with the bank but does no...,0.3211,-0.6871
6997,6997,738,2,0.00,2,1,1,170421.12,This customer is a 29-year-old male from Franc...,0,He is an active member and has an estimated sa...,0.7845,0.4019
6998,6998,512,5,0.00,2,1,1,146457.83,This customer is a 40-year-old male from Franc...,0,"He has 2.0 products with the bank, including a...",0.7845,0.6486
6999,6999,732,1,0.00,2,1,1,177783.05,This customer is a 67-year-old female from Spa...,0,She is an active member and has an estimated s...,0.7845,0.4019

In [11]:
cust_labelled.to_csv('A2_customer_churn_labeled_sentiment.csv', index=False)